services:
  - type: web
    name: cosymind-gest
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn cosymind_gest.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cosymind_gest.settings
